---
- name: apply configuration to all nodes
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - apt
    - common
    - users
    - ufw

- name: apply configuration to laptop
  hosts: laptop
  become: yes
  gather_facts: no
  roles:
    - docker

- name: apply configuration to development
  hosts: development
  become: yes
  gather_facts: no
  roles:
    - docker

- name: apply configuration to production
  hosts: production
  become: yes
  gather_facts: no
  roles:
    - nginx
    - mysqld
    - znc
