---
- name: install apt packages for alacritty
  apt:
    name:
      - cmake
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - pkg-config
      - python3

- name: check if alacritty already built
  stat:
    path: "{{ alacritty.src }}/target/release/alacritty"
  register: stat_result

- name: build and install alacritty
  when: not stat_result.stat.exists
  block:
    - git:
        repo: https://github.com/alacritty/alacritty.git
        dest: "{{ alacritty.src }}"
        version: "{{ alacritty.revision }}"
    - shell:
        chdir: "{{ alacritty.src }}"
        cmd: cargo build --release

- name: symlink alacritty
  file:
    src: "{{ alacritty.src }}/target/release/alacritty"
    dest: /usr/local/bin/alacritty
    state: link
