---
- name: install apt packages for i3
  apt:
    name:
      - blueman
      - bluez
      - i3
      - i3-wm
      - light
      - pasystray
      - xinput
      - xserver-xorg-input-libinput

# xinput --list
# xinput --list-props <device>
# xinput --set-prop <device> 'libinput Accel Speed' 1.0
- name: install xorg.conf for libinput.conf
  copy:
    src: 40-libinput.conf
    dest: /etc/X11/xorg.conf.d/40-libinput.conf

# light -A 10
# light -U 10
- name: allow non-root users change screen brightness
  file:
    path: /sys/class/backlight/intel_backlight/brightness
    mode: "0666"
