---
- name: install apt packages for i3
  apt:
    name:
      - i3
      - i3-wm
      - xinput
      - xserver-xorg-input-libinput

# xinput --list
# xinput --list-props <device>
# xinput --set-prop <device> 'libinput Accel Speed' 1.0
- name: install xorg.conf for libinput.conf
  copy:
    src: 40-libinput.conf
    dest: /etc/X11/xorg.conf.d/40-libinput.conf

#- name: check installed i3-gnome revision
#  vars:
#    src: /usr/local/src/i3-gnome
#  shell:
#    cmd: "cat {{ src }}/installed-revision || true"
#  register: installed_revision
#
#- name: build and install i3-gnome
#  vars:
#    revision: 3.36.0
#    src: /usr/local/src/i3-gnome
#  when: installed_revision.stdout.find(revision) == -1
#  block:
#    - git:
#        repo: https://github.com/i3-gnome/i3-gnome.git
#        dest: "{{ src }}/{{ revision }}"
#        version: "{{ revision }}"
