---
- name: install apt packages for st
  apt:
    name:
      - libx11-dev
      - libxft-dev
      - x11proto-dev

- name: check if st already installed
  stat:
    path: /opt/st/bin/st
  register: stat_result

- name: build and install st
  when: not stat_result.stat.exists
  vars:
    src: /opt/src/st
    prefix: /opt/st
  block:
    - git:
        repo: https://git.suckless.org/st
        dest: "{{ src }}"
    - copy:
        src: st-config.h
        dest: "{{ src }}/config.h"
    - make:
        chdir: "{{ src }}"
        target: clean
    - make:
        chdir: "{{ src }}"
        target: all
        params:
          PREFIX: "{{ prefix }}"
    - make:
        chdir: "{{ src }}"
        target: install
        params:
          PREFIX: "{{ prefix }}"

- name: symlink st
  file:
    src: /opt/st/bin/st
    dest: /usr/local/bin/st
    state: link
