- name: set up apt sources
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list

- name: update apt cache
  apt:
    update_cache: yes

- name: install apt-related packages
  apt:
    name:
      - apt-file

- name: update apt-file cache
  command:
    cmd: apt-file update
