- name: add group znc
  group:
    name: znc
    gid: 2001

- name: add user znc
  user:
    name: znc
    uid: 2001
    group: znc
    shell: "/usr/bin/false"
    home: "/home/znc"

- name: add group www-user
  group:
    name: www-user
    gid: 1100

- name: add user www-user
  user:
    name: www-user
    uid: 1100
    group: www-user
    shell: "/usr/bin/false"
    home: "/home/www-user"

- name: add group docker
  group:
    name: docker
    gid: 2002

- name: add develoers to docker group
  user:
    name: "{{ item }}"
    groups:
      - docker
  with_items: "{{ developers }}"
