- name: install apt packages for erlang
  apt:
    name:
      - erlang

- name: fetch and install rebar3
  get_url:
    url: https://s3.amazonaws.com/rebar3/rebar3
    dest: /usr/local/bin/rebar3
    mode: "0755"
