- name: install apt packages for erlang
  apt:
    name:
      - erlang
      - libssl-dev

## erlang
- name: check installed erlang revision
  shell:
    cmd: "cat {{ erlang.src }}/installed-revision || true"
  register: installed_revision

- name: build and install erlang
  when: installed_revision.stdout.find(erlang.revision) == -1
  block:
    - git:
        repo: https://github.com/erlang/OTP.git
        dest: "{{ erlang.src }}"
        version: "{{ erlang.revision }}"
    - shell:
        chdir: "{{ erlang.src }}"
        cmd: ./otp_build autoconf
    - shell:
        chdir: "{{ erlang.src }}"
        cmd: "./configure --prefix={{ erlang.prefix }}"
    - make:
        chdir: "{{ erlang.src }}"
        target: clean
    - make:
        chdir: "{{ erlang.src }}"
        target: all
    - file:
        path: "{{ erlang.prefix }}"
        state: absent
    - make:
        chdir: "{{ erlang.src }}"
        target: install
    - copy:
        dest: "{{ erlang.src }}/installed-revision"
        content: "{{ erlang.revision }}"

## rebar3
- name: check installed rebar3 revision
  shell:
    cmd: "cat {{ rebar3.src }}/installed-revision || true"
  register: installed_revision

- name: build and install rebar3
  when: installed_revision.stdout.find(rebar3.revision) == -1
  block:
    - git:
        repo: https://github.com/erlang/rebar3.git
        dest: "{{ rebar3.src }}"
        version: "{{ rebar3.revision }}"
    - shell:
        chdir: "{{ rebar3.src }}"
        cmd: "PATH={{ erlang.prefix }}:$PATH ./bootstrap"
    - copy:
        dest: /usr/local/bin/rebar3
        src: "{{ rebar3.src }}/rebar3"
        mode: "0755"
    - copy:
        dest: "{{ rebar3.src }}/installed-revision"
        content: "{{ rebar3.revision }}"
