- name: install apt packages for erlang
  apt:
    name:
      - erlang
      - libssl-dev

- name: check installed erlang revision
  shell:
    cmd: "cat {{ erlang.src }}/installed-revision || true"
  register: installed_revision

- name: build and install erlang
  when: installed_revision.stdout.find(erlang.revision) == -1
  block:
    - git:
        repo: https://github.com/erlang/OTP.git
        dest: "{{ erlang.src }}"
        version: "{{ erlang.revision }}"
    - shell:
        chdir: "{{ erlang.src }}"
        cmd: ./otp_build autoconf
    - shell:
        chdir: "{{ erlang.src }}"
        cmd: "./configure --prefix={{ erlang.prefix }}"
    - make:
        chdir: "{{ erlang.src }}"
        target: clean
    - make:
        chdir: "{{ erlang.src }}"
        target: all
    - file:
        path: "{{ erlang.prefix }}"
        state: absent
    - make:
        chdir: "{{ erlang.src }}"
        target: install
    - copy:
        dest: "{{ erlang.src }}/installed-revision"
        content: "{{ erlang.revision }}"

- include: rebar3.yml
