- name: install apt packages for erlang
  apt:
    name:
      - erlang

- name: check installed erlang revision
  vars:
    src: /opt/src/erlang
  shell:
    cmd: "cat {{ src }}/installed-revision || true"
  register: installed_revision

- name: build and install erlang
  vars:
    revision: OTP-23.0.1
    src: /opt/src/erlang
    prefix: /opt/erlang
  when: installed_revision.stdout.find(revision) == -1
  block:
    - git:
        repo: https://github.com/erlang/OTP.git
        dest: "{{ src }}"
        version: "{{ revision }}"
    - shell:
        chdir: "{{ src }}"
        cmd: ./otp_build autoconf
    - shell:
        chdir: "{{ src }}"
        cmd: "./configure --prefix={{ prefix }}"
    - make:
        chdir: "{{ src }}"
        target: clean
    - make:
        chdir: "{{ src }}"
        target: all
    - file:
        path: "{{ prefix }}"
        state: absent
    - make:
        chdir: "{{ src }}"
        target: install
    - copy:
        dest: "{{ src }}/installed-revision"
        content: "{{ revision }}"

- name: fetch and install rebar3
  get_url:
    url: https://s3.amazonaws.com/rebar3/rebar3
    dest: /opt/erlang/bin/rebar3
    mode: "0755"
