- name: install apt packages for erlang
  apt:
    name:
      - erlang
      - libssl-dev

## erlang
- name: check installed erlang revision
  vars:
    src: /opt/src/erlang
  shell:
    cmd: "cat {{ src }}/installed-revision || true"
  register: installed_revision

- name: build and install erlang
  vars:
    revision: OTP-23.0.2
    src: /opt/src/erlang
    prefix: /opt/erlang
  when: installed_revision.stdout.find(revision) == -1
  block:
    - git:
        repo: https://github.com/erlang/OTP.git
        dest: "{{ src }}"
        version: "{{ revision }}"
    - shell:
        chdir: "{{ src }}"
        cmd: ./otp_build autoconf
    - shell:
        chdir: "{{ src }}"
        cmd: "./configure --prefix={{ prefix }}"
    - make:
        chdir: "{{ src }}"
        target: clean
    - make:
        chdir: "{{ src }}"
        target: all
    - file:
        path: "{{ prefix }}"
        state: absent
    - make:
        chdir: "{{ src }}"
        target: install
    - copy:
        dest: "{{ src }}/installed-revision"
        content: "{{ revision }}"

## rebar3
- name: check installed rebar3 revision
  vars:
    src: /opt/src/rebar3
  shell:
    cmd: "cat {{ src }}/installed-revision || true"
  register: installed_revision

- name: build and install rebar3
  vars:
    revision: 3.13.2
    src: /opt/src/rebar3
    erlang_prefix: /opt/erlang/bin
  when: installed_revision.stdout.find(revision) == -1
  block:
    - git:
        repo: https://github.com/erlang/rebar3.git
        dest: "{{ src }}"
        version: "{{ revision }}"
    - shell:
        chdir: "{{ src }}"
        cmd: "PATH={{ erlang_prefix }}:$PATH ./bootstrap"
    - copy:
        dest: /usr/local/bin/rebar3
        src: "{{ src }}/rebar3"
        mode: "0755"
    - copy:
        dest: "{{ src }}/installed-revision"
        content: "{{ revision }}"
