- name: set time zone
  file:
    src: /usr/share/zoneinfo/Asia/Tokyo
    dest: /etc/localtime
    state: link
    force: yes

- name: install packages
  apt:
    name:
      - autoconf
      - automake
      - bind9-dnsutils
      - bison
      - build-essential
      - ca-certificates
      - checkinstall
      - clang
      - cmake
      - composer
      - cronolog
      - curl
      - finger
      - flex
      - g++
      - gawk
      - git
      - golang
      - gpg
      - htop
      - jq
      - links
      - lynx
      - man
      - netbase
      - php-cli
      - php-xml
      - pkg-config
      - ripgrep
      - rsync
      - ruby
      - ruby-dev
      - speedtest-cli
      - sqlite3
      - sqlite3-doc
      - sqlite3-pcre
      - tmux
      - traceroute
      - tree
      - tzdata
      - uuid-runtime
      - valgrind
      - whois
      - weechat
      - zip
      - zsh

- name: install apt lib packages
  apt:
    name:
      - libdb-dev

- include: awscli.yml
- include: erlang.yml
- include: mysql.yml
- include: neovim.yml
- include: nodejs.yml
- include: perl.yml
- include: protobuf.yml
- include: psql.yml
- include: python.yml
- include: rust.yml
- include: travis.yml
- include: sysstat.yml
- include: universal-ctags.yml
- include: zig.yml
