- name: set time zone
  file:
    src: /usr/share/zoneinfo/Asia/Tokyo
    dest: /etc/localtime
    state: link
    force: yes

- name: install apt packages
  apt:
    name:
      - apt-file
      - autoconf
      - automake
      - awscli
      - bind9-dnsutils
      - bison
      - build-essential
      - ca-certificates
      - checkinstall
      - clang
      - cmake
      - composer
      - cronolog
      - curl
      - finger
      - flex
      - g++
      - gawk
      - git
      - golang
      - htop
      - jq
      - man
      - netbase
      - php-cli
      - php-xml
      - pkg-config
      - python3
      - ripgrep
      - ruby
      - ruby-dev
      - tmux
      - traceroute
      - tree
      - tzdata
      - uuid-runtime
      - valgrind
      - whois
      - weechat
      - zip
      - zsh

- name: install apt lib packages
  apt:
    name:
      - libdb-dev
      - libprotobuf-dev

- include: erlang.yml
- include: mysql.yml
- include: neovim.yml
- include: nodejs.yml
- include: perl.yml
- include: psql.yml
- include: rust.yml
- include: travis.yml
- include: sysstat.yml
- include: universal-ctags.yml
