- name: check installed zig revision
  shell:
    cmd: "(/opt/zig/zig version || true) 2>/dev/null"
  register: installed_revision

- name: fetch and install zig
  when: installed_revision.stdout.find(zig.revision) == -1
  block:
    - file:
        path: "{{ zig.src }}"
        state: directory
        mode: "0755"
    - file:
        path: "{{ zig.prefix }}"
        state: directory
        mode: "0755"
    - get_url:
        url: "https://ziglang.org/builds/zig-linux-x86_64-{{ zig.revision }}.tar.xz"
        dest: "{{ zig.src }}/zig-{{ zig.revision }}.tar.xz"
        mode: "0644"
    - unarchive:
        src: "{{ zig.src }}/zig-{{ zig.revision }}.tar.xz"
        dest: "{{ zig.prefix }}"
        extra_opts: [--strip-components=1]
