- name: check installed zig revision
  shell:
    cmd: "(/opt/zig/zig version || true) 2>/dev/null"
  register: installed_revision

- name: check the latest zig version
  shell:
    cmd: "curl -sSL https://ziglang.org/download/index.json | jq -r .master.version"
  register: latest_revision

- name: fetch and install zig
  when: latest_revision.stdout.find(installed_revision.stdout) == -1
  block:
    - file:
        path: "{{ zig.src }}"
        state: directory
        mode: "0755"
    - file:
        path: "{{ zig.prefix }}"
        state: directory
        mode: "0755"
    - get_url:
        url: "https://ziglang.org/builds/zig-linux-x86_64-{{ latest_revision.stdout }}.tar.xz"
        dest: "{{ zig.src }}/zig-{{ latest_revision.stdout }}.tar.xz"
        mode: "0644"
    - unarchive:
        src: "{{ zig.src }}/zig-{{ latest_revision.stdout }}.tar.xz"
        dest: "{{ zig.prefix }}"
        extra_opts: [--strip-components=1]
