- name: install docker.io
  apt:
    name:
      - docker.io
      - docker-compose

- name: enable docker service
  systemd:
    name: docker
    enabled:  yes

- name: start docker service
  systemd:
    name: docker
    state: started
